### ISSUE TITLE
BAL tool script not working in Arcgis environment

### ISSUE THREAD

**Issue by AgnesKristina** [GeoscienceAustralia/BAL#3]
Tried to run the latest BAL Tool and received this error:
Traceback (most recent call last):
  File "H:\BAL_GA\BAL-master\bal.py", line 21, in <module>
    from utilities.sa_tools import extract_by_mask, reclassify, cal_slope_aspect
  File "H:\BAL_GA\BAL-master\utilities\sa_tools.py", line 17, in <module>
    from scipy import ndimage
ImportError: No module named scipy

Failed to execute (BAL).

Assistance will be greatly appreciated and thank you

**Comment by wcarthur** [comment]
This has been resolved in the latest updates (3cae52c) 

Download the updated code from https://github.com/GeoscienceAustralia/BAL using the Clone or Download button.
