### ISSUE TITLE
Links to AS 3959 are incorrect

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/BAL#4]
Need to update the hyperlinks in the documentation that point to http://www.as3959.com.au - this is an unofficial site that is intended to make it easier for people to locate the standard. Officially, we should only link to the Standards Online version. 

The correct link is actually: https://www.saiglobal.com/online/Script/Details.asp?DocN=AS819920597136

**Comment by CEKrause** [comment]
Fixed :+1:
